### ISSUE TITLE
Add http proxy

### ISSUE THREAD

**Issue by pharaoh347** [Freddywhest/RockyRabbitBot#12]

**Comment by Freddywhest** [comment]
It's already supported, test your proxies if they are working before using it with the script

**Comment by pharaoh347** [comment]
how can i install them if in the proxies.js file there is only a choice socks5/socks4

**Comment by Freddywhest** [comment]
If your proxies are premium, replace http with socks5 and try it

**Comment by pharaoh347** [comment]
> If your proxies are premium, replace http with socks5 and try it

![image](https://github.com/user-attachments/assets/5b3cc848-8e6f-442c-83a9-36f7ba0e2606)

**Comment by Freddywhest** [comment]
Fixed. Update to the latest version and try again
