### ISSUE TITLE
some problems in bot

### ISSUE THREAD

**Issue by mrxt0098** [Freddywhest/RockyRabbitBot#15]
Hello and thank you for your good bot, the robot works well, but it has a few problems, one is that it does not receive the coins of most of the cards, and two, it does not find the hidden Easter eggs. If you can fix this, I would be very grateful.
![Screenshot_20240903-101701_Telegram](https://github.com/user-attachments/assets/b14d01ce-511e-48c6-bc41-fc2a02072229)
![Screenshot_20240903-101337_Telegram](https://github.com/user-attachments/assets/1a397dde-64af-4e89-b626-6a8b88387316)

**Comment by Freddywhest** [comment]
For the combos look at this issue for an answer to https://github.com/Freddywhest/RockyRabbitBot/issues/14#issuecomment-2325412699
