### ISSUE TITLE
Card coin claim not work

### ISSUE THREAD

**Issue by mrxt0098** [Freddywhest/RockyRabbitBot#16]
As I say before
the bot work perfectly 
But a function claiming cards coins not work as you  can see on screenshot pls fix that
![Screenshot_20240903-101337_Telegram](https://github.com/user-attachments/assets/5ad9e79f-ffa4-4cd0-a570-db98e24513de)

**Comment by Freddywhest** [comment]
It hasn't been implemented, and there are no plans to add it at this time.
