### ISSUE TITLE
Token expires in 2 hours

### ISSUE THREAD

**Issue by Drsexo** [Freddywhest/RockyRabbitBot#18]
![image](https://github.com/user-attachments/assets/14026170-81e2-401f-b42b-c47e818b91b2)
Is there any way to add a "auto refresh token" option ? this happens every 2 hours

**Comment by promaxuz** [comment]
![image](https://github.com/user-attachments/assets/02befa04-3aa1-4587-8568-591ba8efbee8)
how to fixx  brooo

**Comment by Freddywhest** [comment]
The only way to automatically refresh the token is by using a session

**Comment by poein** [comment]
> The only way to automatically refresh the token is by using a session

Hi @Freddywhest , how can I refresh the token by using a session
