### ISSUE TITLE
 Error while getting daily sync info: write EPROTO 00BDB9DC077F0000:error:0A000410:SSL routines:ssl3_read_bytes:sslv3 alert handshake failure:../deps/openssl/openssl/ssl/record/rec_layer_s3.c:1590:SSL alert number 40

### ISSUE THREAD

**Issue by pharaoh347** [Freddywhest/RockyRabbitBot#19]
![image](https://github.com/user-attachments/assets/ea8dd0f3-d5db-4cf9-bcec-8f2898ddee73)

**Comment by Freddywhest** [comment]
This issue doesn't seem to be related to the bot. Which operating system are you using? Is it a cloud-based machine or a personal computer?

**Comment by pharaoh347** [comment]
Ubuntu 22.04
Cloud

**Comment by Freddywhest** [comment]
Search for something like on google "handshake failure:../deps/openssl/openssl/ssl/record/rec_layer_s3.c:1590
alert number 40 on Ubuntu 22.04 [enter your cloud provider]"
