### ISSUE TITLE
Error 404 when receiving enigma info

### ISSUE THREAD

**Issue by Nord1cWarr1or** [Freddywhest/RockyRabbitBot#2]
`[2024-08-13 17:56:17] | ERROR | sergey | Error while getting enigma info: Request failed with status code 404
`

**Comment by ngocbae98** [comment]
same problem
Error while getting combo info: Request failed with status code 404

**Comment by zhengchuan82** [comment]
Same issue here.

**Comment by Freddywhest** [comment]
Issue fixed, update to the latest version
