### ISSUE TITLE
erorr

### ISSUE THREAD

**Issue by pharaoh347** [Freddywhest/RockyRabbitBot#27]
![image](https://github.com/user-attachments/assets/7f411bd1-db61-4318-9b94-af029668bd56)

**Comment by Freddywhest** [comment]
Run `npm install`

**Comment by Freddywhest** [comment]
Update it again and run `npm install`

**Comment by pharaoh347** [comment]
> Update it again and run `npm install`

how use socks proxy?

**Comment by pharaoh347** [comment]
![image](https://github.com/user-attachments/assets/c9897d22-bedf-425c-bc93-f594422f65d9)

**Comment by Freddywhest** [comment]
Try without proxy, if it works

**Comment by pharaoh347** [comment]
> Try without proxy
![image](https://github.com/user-attachments/assets/41081a4e-b627-4603-8791-4ffc19f435db)

**Comment by painterzeou** [comment]
Same issue And I'm not using proxy

**Comment by Freddywhest** [comment]
Fixed
