### ISSUE TITLE
new problem

### ISSUE THREAD

**Issue by parafius** [Freddywhest/RockyRabbitBot#32]
![image](https://github.com/user-attachments/assets/bb3127b7-aee4-417c-975c-516b574bae99)

**Comment by parafius** [comment]
![image](https://github.com/user-attachments/assets/be21ec14-9230-400a-9cde-3c1371ca04cf)
after update, new)

**Comment by Freddywhest** [comment]
Refer to this telegram message: https://t.me/freddy_bots/75
