### ISSUE TITLE
Error 401. Last update

### ISSUE THREAD

**Issue by GeRRyOD** [Freddywhest/RockyRabbitBot#33]
![image](https://github.com/user-attachments/assets/b00c88f3-3083-4609-87a2-643d1e1fc0e5)

**Comment by Freddywhest** [comment]
You are using invalid query id

**Comment by GeRRyOD** [comment]
How can i Take right query?

ср, 11 сент. 2024 г., 11:55 Alfred Nti ***@***.***>:

**Comment by Freddywhest** [comment]
Check the readme of this repository
