### ISSUE TITLE
card claim problem

### ISSUE THREAD

**Issue by mrxt0098** [Freddywhest/RockyRabbitBot#37]
the bot work perfectly
But a function claiming cards coins not work as you can see on screenshot pls fix that
![image](https://github.com/user-attachments/assets/6b7fb67c-c5b6-4ea2-a893-3b7b45be6990)

**Comment by Freddywhest** [comment]
The bot only claims the tournament, fighter > upgrade, fighter > venture and coach > upgrade cards at the moment
