### ISSUE TITLE
combo, easter egg, timeout issue

### ISSUE THREAD

**Issue by ashtrobe** [Freddywhest/RockyRabbitBot#41]
it doesnt seem to automatically complete enigma and combos. upgrading cards and getting random "Error while getting User Data: Timeout awaiting 'request' for 60000ms"

can you provide any solution?

update: it did complete the enigma but not the combo and easter egg. gets timed out, can you tell me where can i edit the time out setting and increase it

![image](https://github.com/user-attachments/assets/62aeec3a-854c-413d-8ae2-228acefbfe92)

It keeps tapping, and the wait's for tap then repeats the process, not doing anything else

**Comment by ashtrobe** [comment]
update: it did complete the enigma but not the combo and easter egg. gets timed out, can you tell me where can i edit the time out setting and increase it

**Comment by ashtrobe** [comment]
![image](https://github.com/user-attachments/assets/dbe1cffa-77a5-4f3c-9de4-7d1260330222)

**Comment by Freddywhest** [comment]
Fixed
