### ISSUE TITLE
Hi, could you add claim dailys?

### ISSUE THREAD

**Issue by FarmTon** [Freddywhest/RockyRabbitBot#7]
Bot works fine, it just doesnt claim daily ( Claims breakfast but doesnt claim most of them) 

py:  
def do_daily_tasks(self):
        upgrades = self.mine_upgrade_sync()
        for upgrade in upgrades:
            if upgrade['type'] == 'daily' and time.time() - upgrade['lastUpgradeAt'] > 24 * 60 * 60 :
                result = self.mine_upgrade(upgrade['upgradeId'])
                if 'clicker' in result:
                    self.logger.info(f"[+] Task: {upgrade['upgradeId']} | Balance: {result['clicker']['balance']}")
                else:
                    self.logger.error(f"[-] Error in task: {upgrade['upgradeId']} | clicker data not found")

java:
        async function doDailyTasks() {
    const upgrades = await this.mineUpgradeSync();

    upgrades.forEach(upgrade => {
        if (upgrade.type === 'daily' && (Date.now() / 1000) - upgrade.lastUpgradeAt > 24 * 60 * 60) {
            const result = this.mineUpgrade(upgrade.upgradeId);
            if (result.clicker) {
                this.logger.info(`[+] Task: ${upgrade.upgradeId} | Balance: ${result.clicker.balance}`);
            } else {
                this.logger.error(`[-] Error in task: ${upgrade.upgradeId} | clicker data not found`);
            }
        }
    });
}

**Comment by Freddywhest** [comment]
If the code you provided works, make a pull request and lemme merge it

**Comment by Freddywhest** [comment]
The `luncher.js` file is just the banner and text displayed in the terminal when the script starts. For everything you need, check the `core`, `helpers`, `scripts`, and `config` directories. If you're not a JavaScript developer, no worries—I'll handle it.

**Comment by FarmTon** [comment]
> The `luncher.js` file is just the banner and text displayed in the terminal when the script starts. For everything you need, check the `core`, `helpers`, `scripts`, and `config` directories. If you're not a JavaScript developer, no worries—I'll handle it.

Alright good to know thanks, will check later not that experienced on js i focus on py/other languages but can adapt ill learn , thanks again for the help.
