### ISSUE TITLE
erorr

### ISSUE THREAD

**Issue by MGTV01** [Freddywhest/RockyRabbitBot#9]
![image](https://github.com/user-attachments/assets/d8dd5506-e2e2-4e5d-976c-4df912ec6f0e)
Hi engineer, I went through all the steps, but at the end I got this error. How to fix this error?

**Comment by Freddywhest** [comment]
Are you using sessions or query_id

**Comment by MGTV01** [comment]
> آیا از sessions یا query_id استفاده می کنید؟

Hi, engineer. Yes, I took action according to your document to get the query_id. And I went and put it in the queryIds.json file. But I got an error.

**Comment by Freddywhest** [comment]
Have you set USE_QUERY_ID=True?

**Comment by MGTV01** [comment]
> Have you set USE_QUERY_ID=True?
![image](https://github.com/user-attachments/assets/42de2d8a-25ac-4e7b-871b-ebc5883f7512)
.env settings
![image](https://github.com/user-attachments/assets/6c08b92e-6211-44de-8f98-b085a28eee52)
Error during execution
Is there a solution?

**Comment by Freddywhest** [comment]
Send me a picture of session_user_agents.json

**Comment by MGTV01** [comment]
> یک عکس از session_user_agents.json برای من بفرستید

![image](https://github.com/user-attachments/assets/b96d16bf-8437-4994-82ef-ce091d121246)
The queryIds.json file, which contains my token. Did you mean this? Of course, there was more, but I confused it.

**Comment by Freddywhest** [comment]
Which nodejs version are you using?

**Comment by MGTV01** [comment]
> Which nodejs version are you using?

v12.22.9
Should I call an engineer to implement the project?

**Comment by Freddywhest** [comment]
Please use nodejs 18 to 20

**Comment by MGTV01** [comment]
> لطفا از nodejs 18 تا 20 استفاده کنید

What is the installation command? What is the installation command please??

**Comment by Freddywhest** [comment]
Which operating system are you using?

**Comment by MGTV01** [comment]
> از کدام سیستم عامل استفاده می کنید؟

ubuntu server 22

**Comment by Freddywhest** [comment]
To install Node.js 18 on an Ubuntu 22 server that already has Node.js 12 installed, you can follow these steps:

### 1. Update the System Packages
First, update your package list to ensure all repositories and packages are up-to-date:

```bash
sudo apt update
sudo apt upgrade
```

### 2. Install Node.js 18 Using NodeSource
The NodeSource repository provides an easy way to install Node.js versions. You can add the NodeSource repository for Node.js 18 and install it.

```bash
# Remove the existing Node.js 12.x repository if it was added previously
sudo rm /etc/apt/sources.list.d/nodesource.list

# Add the NodeSource repository for Node.js 18.x
curl -fsSL https://deb.nodesource.com/setup_18.x | sudo -E bash -

# Install Node.js 18
sudo apt install -y nodejs
```

### 3. Verify the Installation
After the installation is complete, you can check the installed version of Node.js and npm:

```bash
node -v
npm -v
```

### 4. (Optional) Use `nvm` for Managing Node.js Versions
If you want to maintain multiple versions of Node.js (e.g., Node.js 12 and Node.js 18) and switch between them easily, you can use `nvm` (Node Version Manager):

1. **Install `nvm`:**
   ```bash
   curl -o- https://raw.githubusercontent.com/nvm-sh/nvm/v0.39.3/install.sh | bash
   ```

   After installation, run the following to add `nvm` to your shell profile:
   ```bash
   export NVM_DIR="$([ -z "${XDG_CONFIG_HOME-}" ] && printf %s "${HOME}/.nvm" || printf %s "${XDG_CONFIG_HOME}/nvm")"
   [ -s "$NVM_DIR/nvm.sh" ] && \. "$NVM_DIR/nvm.sh" # This loads nvm
   ```

2. **Install Node.js 18 using `nvm`:**
   ```bash
   nvm install 18
   ```

3. **Switch between Node.js versions:**
   ```bash
   nvm use 18  # Switch to Node.js 18
   nvm use 12  # Switch back to Node.js 12
   ```

This approach allows you to maintain multiple versions of Node.js on your system and switch between them as needed.

**Comment by MGTV01** [comment]
> To install Node.js 18 on an Ubuntu 22 server that already has Node.js 12 installed, you can follow these steps:
> 
> ### 1. Update the System Packages
> First, update your package list to ensure all repositories and packages are up-to-date:
> 
> ```shell
> sudo apt update
> sudo apt upgrade
> ```
> 
> ### 2. Install Node.js 18 Using NodeSource
> The NodeSource repository provides an easy way to install Node.js versions. You can add the NodeSource repository for Node.js 18 and install it.
> 
> ```shell
> # Remove the existing Node.js 12.x repository if it was added previously
> sudo rm /etc/apt/sources.list.d/nodesource.list
> 
> # Add the NodeSource repository for Node.js 18.x
> curl -fsSL https://deb.nodesource.com/setup_18.x | sudo -E bash -
> 
> # Install Node.js 18
> sudo apt install -y nodejs
> ```
> 
> ### 3. Verify the Installation
> After the installation is complete, you can check the installed version of Node.js and npm:
> 
> ```shell
> node -v
> npm -v
> ```
> 
> ### 4. (Optional) Use `nvm` for Managing Node.js Versions
> If you want to maintain multiple versions of Node.js (e.g., Node.js 12 and Node.js 18) and switch between them easily, you can use `nvm` (Node Version Manager):
> 
> 1. **Install `nvm`:**
>    ```shell
>    curl -o- https://raw.githubusercontent.com/nvm-sh/nvm/v0.39.3/install.sh | bash
>    ```
>    
>    
>        
>          
>        
>    
>          
>        
>    
>        
>      
>    After installation, run the following to add `nvm` to your shell profile:
>    ```shell
>    export NVM_DIR="$([ -z "${XDG_CONFIG_HOME-}" ] && printf %s "${HOME}/.nvm" || printf %s "${XDG_CONFIG_HOME}/nvm")"
>    [ -s "$NVM_DIR/nvm.sh" ] && \. "$NVM_DIR/nvm.sh" # This loads nvm
>    ```
> 2. **Install Node.js 18 using `nvm`:**
>    ```shell
>    nvm install 18
>    ```
> 3. **Switch between Node.js versions:**
>    ```shell
>    nvm use 18  # Switch to Node.js 18
>    nvm use 12  # Switch back to Node.js 12
>    ```
> 
> This approach allows you to maintain multiple versions of Node.js on your system and switch between them as needed.

Hello, engineer. On my other account, the robot was successfully executed by creating a session. But on my main account, when I entered a command with the Telegram web console, there was a problem in such a way that the robot does not run even after creating a session. There is a solution in the Telegram console settings. Webbot reset rabbit to default so I can use session creation again?

**Comment by MGTV01** [comment]
![image](https://github.com/user-attachments/assets/22abb5c1-4187-4150-a7b7-0021b302c556)

**Comment by Freddywhest** [comment]
Leave like 10 - 20 channels you are currently joining so that it can join rocky rabbit channel to claim daily rewards

**Comment by MGTV01** [comment]
> 10 تا 20 کانالی را که در حال حاضر به آنها ملحق شده اید ترک کنید تا بتواند به کانال Rocky rabbit بپیوندد و جوایز روزانه را دریافت کند.

Thank you, engineer. It was done
